name: dataracescheck
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  helgrind:
    runs-on: ubuntu-latest
    name: 42helgrind
    steps:
    - uses: actions/checkout@v2
    - name: 42helgrind data reaces checker
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: 'make dataracescheck -C philo'