# .github/workflows/valgrind.yml
name: memcheck-docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    name: 42valgrind
    steps:
    - uses: actions/checkout@v2
    - name: 42valgrind Leak checker
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: 'make memcheck'